Issue #2431 - Upgrade to Junit 5
Attempt to fix ...
java.lang.ClassNotFoundException: org.hamcrest.Matchers cannot be found by PAXEXAM-PROBE-d986addc-4704-4445-a9dd-e7d858f64740_0.0.0
at org.eclipse.jetty.osgi.test.TestJettyOSGiBootHTTP2.testHTTP2(TestJettyOSGiBootHTTP2.java:175)